// <auto-generated />
namespace DG.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20180822_editSU_HA : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20180822_editSU_HA));
        
        string IMigrationMetadata.Id
        {
            get { return "201808220606577_20180822_editSU_HA"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
