// <auto-generated />
namespace DG.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _19082018_DuongHH : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_19082018_DuongHH));
        
        string IMigrationMetadata.Id
        {
            get { return "201808191617514_19082018_DuongHH"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
